name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout cod
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Login in Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t prodactil/flask-app:latest ./app

    # 4️⃣ Push Docker image
    - name: Push Docker image
      run: docker push prodactil/flask-app:latest

    # 5️⃣ Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # 6️⃣ Apply Kubernetes manifests
    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/deployment.yaml
